const auth = require('express').Router();
const signup = require('../controllers/auth/signup');
const login = require('../controllers/auth/login');
const authMiddleware = require('../middleware/auth');
const continueIfAuthenticated = require('../controllers/auth/continueIfAuthenticated');
const customLogin = require('../controllers/auth/customLogin');
auth.post('/signup', signup);
auth.post('/login', login);
auth.post('/customLogin', customLogin);
auth.get('/continueIfAuthenticated', authMiddleware, continueIfAuthenticated);
auth.post('logout', authMiddleware);
module.exports = auth;